// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWnwmmu_0Bv5MjJRVfn4T3tnUxQ-8bEEQ',
    appId: '1:295067588344:web:ed2c91f7acdb83b8838d0d',
    messagingSenderId: '295067588344',
    projectId: 'inventory-app-8790b',
    authDomain: 'inventory-app-8790b.firebaseapp.com',
    storageBucket: 'inventory-app-8790b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx5BDeX7Ce6GMlEIhh4MCLJoX41q37_Ak',
    appId: '1:295067588344:android:de3b17d7d073d7de838d0d',
    messagingSenderId: '295067588344',
    projectId: 'inventory-app-8790b',
    storageBucket: 'inventory-app-8790b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Qlj7ktNeOgW6a7BMOWZ-5JXOqDy6ibE',
    appId: '1:295067588344:ios:4496c3e23f5bd73a838d0d',
    messagingSenderId: '295067588344',
    projectId: 'inventory-app-8790b',
    storageBucket: 'inventory-app-8790b.firebasestorage.app',
    iosBundleId: 'com.example.inventory.app.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Qlj7ktNeOgW6a7BMOWZ-5JXOqDy6ibE',
    appId: '1:295067588344:ios:e72f34cf16df142c838d0d',
    messagingSenderId: '295067588344',
    projectId: 'inventory-app-8790b',
    storageBucket: 'inventory-app-8790b.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWnwmmu_0Bv5MjJRVfn4T3tnUxQ-8bEEQ',
    appId: '1:295067588344:web:ae9f572da389a4c8838d0d',
    messagingSenderId: '295067588344',
    projectId: 'inventory-app-8790b',
    authDomain: 'inventory-app-8790b.firebaseapp.com',
    storageBucket: 'inventory-app-8790b.firebasestorage.app',
  );

}